title: Теневой раб
url: "https://shadowslave.ru"
baseurl: ""
author: Guiltythree

defaults:
  - scope:
      path: ""
    values:
      description: >-
        Все главы новеллы Теневой раб доступны на русском языке бесплатно. Вас ждет удобный формат для чтения, регулярные обновления, быстрый доступ к любимым главам и возможность читать без интернета.
  - scope:
      path: "_chapters"
      type: "chapters"
    values:
      description: >-
        Глава новеллы Теневой раб. Читайте бесплатно на русском языке с удобной навигацией между главами.

lang: ru

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  chapters:
    output: true
    permalink: /chapters/:name/
    sort_by: name
  pages:
    output: true

sass:
  load_paths:
    - _sass
    - assets/css

exclude:
  - Rakefile
  - vendor/
